version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      pnpm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    groups:
      gradle-dependencies:
        patterns:
          - '*'

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
