# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ByteowlsCapacitorFilesharer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteowlsCapacitorFilesharer
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'

end
